[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "spaces"
author = "Jp Hayek"
author-email = "jphayek1@gmail.com"
classifiers = ["License :: OSI Approved :: MIT License"]

